apiVersion: apps/v1
kind: Deployment
metadata:
  name: captureorderack-deployment
  labels:
    app: captureorderack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: captureorderack
  template:
    metadata:
      labels:
        app: captureorderack
    spec:
      containers:
      - name: captureorderack
        image: torosent/captureorderack
        ports:
        - containerPort: 8080
        env:
          - name: TEAMNAME
            value: TeamBlue
          - name: CHALLENGEAPPINSIGHTS_KEY
            value: "73f1a101-984f-4e38-b24b-b9e2a7092582"
          - name: MONGOURL
            value: "mongodb://mongodb-mongodb.default.svc.cluster.local"
