#
# Create AKS
#
# Export env variables:
#   AZURE_CLIENT_ID
#   AZURE_CLIENT_SECRET

- name: Create AKS in northern europe
  hosts: localhost
  connection: local
  vars:
    ssh_key: "{{ lookup('file', '~/.ssh/azure.pub') }}"
    resource_group: TeamBlueResourceGroup-NorthernEurope
    location: northeurope
    aks_name: TeamBlue-NorthernEurope
    username: teamblue
    client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    client_secret: "{{ lookup('env', 'AZURE_CLIENT_SECRET') }}"
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"

  - name: Create AKS cluster
    azure_rm_aks:
      name: "{{ aks_name }}"
      location: "northeurope"
      resource_group: "{{ resource_group }}"
      dns_prefix: "{{ aks_name }}"
      linux_profile:
        admin_username: "{{ username }}"
        ssh_key: "{{ ssh_key }}"
      service_principal:
        client_id: "{{ client_id }}"
        client_secret: "{{ client_secret }}"
      agent_pool_profiles:
        - name: default
          count: 3
          vm_size: Standard_D2_v2
      tags:
        Environment: TeamBlue
        TEAMNAME: TeamBlue
        CHALLENGEAPPINSIGHTS_KEY: 
